# Generated by Django 5.0.3 on 2025-04-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='airQuality',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
